### ISSUE TITLE
flask-mongokit cannot be used outside a request.

### ISSUE THREAD

**Issue by davidovich** [jarus/flask-mongokit#4]
Because of the use of _request_ctx_stack to store the current connection, db forwarding mechanism (__getattr__) is broken when no request is active.

For example, in a test without a flask test_client, I want to use the db = MongoKit(app) object like so:

db.User.find_one({'name': name})
which results in an AttributeError: 'NoneType' object has no attribute 'mongokit_connection'

**getattr**() tries to connect to database and wants to add mongokit_connection attribute to the current ctx.

I propose to decouple the connection from the context and keep the connection (and Database) as an attribute of the MongoKit object. This would allow for seamless usage of the db object as intended. In essence, replace ctx with self in the connect method and drop the usage of _request_context_stack

**Comment by jarus** [comment]
Thanks for the pull request! More under #5

**Comment by jmcantrell** [comment]
This doesn't work for me. I still get the exact error message detailed above.

EDIT: It appears the latest code is not on pypi. Any updates on that?

**Comment by jarus** [comment]
I will bump the version number and upload the version to PyPi.

**Comment by jarus** [comment]
Done.

**Comment by jmcantrell** [comment]
Thanks!
