### ISSUE TITLE
Integrate with Flask-Debugtoolbar

### ISSUE THREAD

**Issue by cenkalti** [jarus/flask-mongokit#6]

**Comment by jarus** [comment]
It would be a nice feature but I never used the debugtoolbar so I would not the right one for coding an implementation.

**Comment by cenkalti** [comment]
Actually, the toolbar part is easy, I can handle it but, the thing is there is no query logging or hook mechanism in mongodb python driver. I asked in official issue tracker for mongodb but, they couldn't help either.

https://jira.mongodb.org/browse/PYTHON-352

Maybe it can be achieved by monkey patching?
